In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9574074074074074

In [4]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9833333333333333

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9685185185185186

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,]):
    print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
get_score(LogisticRegression(),X_train, X_test, y_train, y_test)

0.9574074074074074

In [10]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [11]:
scores_l = []
scores_svm=[]
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index],\
                                       digits.target[train_index],digits.target[test_index]
    
    
    scores_l.append(get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train, X_test, y_train, y_test))

In [12]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [13]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [14]:
scores_rf

[0.9332220367278798, 0.9549248747913188, 0.9215358931552587]

In [15]:
from sklearn.model_selection import cross_val_score

In [19]:
cross_val_score(LogisticRegression(), digits.data, digits.target,cv=3)

array([0.92153589, 0.94156928, 0.91652755])

In [20]:
cross_val_score(SVC(), digits.data, digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)

array([0.92821369, 0.94323873, 0.92153589])

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target,cv=3)

array([0.92654424, 0.95993322, 0.91318865])